<?php
/**
 * Created by PhpStorm.
 * User: zerovan
 * Date: 20/08/2018
 * Time: 10:57 AM
 */

namespace frontend\controllers;
use yii\filters\auth\HttpBasicAuth;
use yii\rest\ActiveController;
use Yii;

class CommenttestController extends ActiveController
{
    public $modelClass = 'frontend\models\Comment';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->user->enableSession = false;
        Yii::$app->user->loginUrl = NULL;

    }

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors ['authenticator'] = [
            'class' => HttpBasicAuth::className(),
            'auth' => function ($username , $password)
            {
                $user = \common\models\User::findByPhone($username);


                if ($user != NULL)
                    if ($user->validatePassword($password))
                    {
                        return $user;
                    }
                    return NULL;
            }
        ];
        return $behaviors;
    }

}